### ISSUE TITLE
death?

### ISSUE THREAD

**Issue by 2peter3** [AntonioVdlC/fantomely#21]
Hey,
is this project death? or still in development?

Thanks

**Comment by AntonioVdlC** [comment]
Hi @2peter3,

Thanks for inquiring about the status of this project. I've been busy with other things over the past few weeks, but I'm still planning on working on this project in the future.

In the meantime, I'm happy to redirect you to other privacy-first web analytics tools available in the market, such as [Fathom](https://usefathom.com/), [Plausible](https://plausible.io/), [Fugu](https://fugu.lol/), or [Pirsch](https://pirsch.io/).

Hope that helps!
